//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Permiso
    {
        public int IdPermiso { get; set; }
        [Required(ErrorMessage = "Este campo es Obligarotio")]
        public int Empleado { get; set; }
        [Required(ErrorMessage = "Este campo es Obligarotio")]
        public Nullable<System.DateTime> Desde { get; set; }
        [Required(ErrorMessage = "Este campo es Obligarotio")]
        public Nullable<System.DateTime> Hasta { get; set; }
        public string Comentarios { get; set; }
    
        public virtual Empleado Empleado1 { get; set; }
    }
}
